
trigger:
- master

pool:
  name: 'AxesNetwork Lab Linux Yocto'

steps:
- checkout: self
  submodules: true
- task: CmdLine@2
  inputs:
    script: |
      sudo -u user ./balena-yocto-scripts/build/barys