
trigger:
- master

pool:
  name: 'AxesNetwork Lab Linux Yocto'

steps:
- checkout: self
  clean: false
  submodules: true
- task: CmdLine@2
  timeoutInMinutes: 1440
  inputs:
    script: |
      sudo chmod -R ugo+rwx .
      sudo su -c "bash ./balena-yocto-scripts/build/barys" user