
trigger:
- master

pool:
  name: 'AxesNetwork Lab Linux Yocto'

steps:
- checkout: self
  clean: false
  submodules: true
- task: CmdLine@2
  timeoutInMinutes: 1440
  inputs:
    script: |
      perm=$(stat -c %a "$f")
      if [ ! "$perm" = "777" ]; then
        sudo chmod -R 777 .
      fi
      sudo su -c "bash ./balena-yocto-scripts/build/barys" user