
trigger:
- master

jobs:
- job: Default
  timeoutInMinutes: 1440
  
  pool:
    name: 'AxesNetwork Lab Linux Yocto'

  steps:
  - checkout: self
    clean: false
    submodules: true
  - task: CmdLine@2
    inputs:
      script: |
        perm=$(stat -c %a $PWD)
        if [ ! "$perm" = "777" ]; then
          sudo chmod -R 777 $PWD
        fi
        sudo su -c "bash ./balena-yocto-scripts/build/barys" user