
trigger:
- master

pool:
  name: 'AxesNetwork Lab Linux Yocto'

steps:
- checkout: self
  clean: false
  submodules: true
- task: CmdLine@2
  timeoutInMinutes: 1440
  inputs:
    script: |
      perms==$(stat $PWD | sed -n '/^Access: (/{s/Access: (\([0-9]\+\).*$/\1/;p}')
      if [[ $perms =~ 777 ]]; then
        sudo chmod -R 777 .
      fi
      sudo su -c "bash ./balena-yocto-scripts/build/barys" user